#pragma once

#include "gdpp/core/source.hpp"

#include <string>

namespace gdpp {

enum class TokenKind {
    end_of_file,
    newline,
    indent,
    dedent,
    identifier,
    integer,
    floating,
    string,
    string_name,
    node_path,
    node_reference,
    kw_extends,
    kw_class_name,
    kw_class,
    kw_func,
    kw_var,
    kw_const,
    kw_signal,
    kw_enum,
    kw_static,
    kw_return,
    kw_assert,
    kw_breakpoint,
    kw_pass,
    kw_if,
    kw_match,
    kw_when,
    kw_elif,
    kw_else,
    kw_while,
    kw_for,
    kw_in,
    kw_break,
    kw_continue,
    kw_true,
    kw_false,
    kw_null,
    kw_self,
    kw_and,
    kw_or,
    kw_not,
    kw_as,
    kw_is,
    kw_await,
    left_paren,
    right_paren,
    left_bracket,
    right_bracket,
    left_brace,
    right_brace,
    at_sign,
    comma,
    dot,
    dot_dot,
    ellipsis,
    colon,
    colon_equal,
    semicolon,
    arrow,
    plus,
    minus,
    star,
    power,
    slash,
    percent,
    equal,
    plus_equal,
    minus_equal,
    star_equal,
    power_equal,
    slash_equal,
    percent_equal,
    equal_equal,
    bang_equal,
    less,
    less_equal,
    greater,
    greater_equal,
    ampersand,
    ampersand_equal,
    pipe,
    pipe_equal,
    caret,
    caret_equal,
    tilde,
    shift_left,
    shift_left_equal,
    shift_right,
    shift_right_equal,
};

struct Token {
    TokenKind kind{TokenKind::end_of_file};
    std::string lexeme;
    SourceSpan span{};
};

[[nodiscard]] const char* token_kind_name(TokenKind kind) noexcept;

} // namespace gdpp
